server:
  port: 3344

spring:
  application:
    name: cloud-payment-dashboard
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
 
eureka:
  instance:
    instance-id: dashboard9001
    prefer-ip-address: true
  #    lease-renewal-interval-in-seconds: 1
  #    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #集群指向其它eureka
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #注册中心地址
      defaultZone: http://localhost:7001/eureka/