server:
  port: 84

spring:
  application:
    name: cloudalibaba-consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos注册中心
    sentinel:
      transport:
        dashboard: localhost:8080 #dashboard默认地址
        port: 8719 #占用后自动加1

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  sentinel:
    enabled: true
