server:
  port: 83

spring:
  application:
    name: service-consumer-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"

service-consumer-nacos:
  addr: http://service-provider-nacos